### ISSUE TITLE
Inconsistency detected by ld.so:../elf/dl-tls.c: 517: dl allocate tls init: Assertion 'listp!= NULL' failed!

### ISSUE THREAD

**Issue by jiangxiaobaiii** [StanfordVL/OmniGibson#1066]
The following is the issue I encountered while running on my laptop. I have reinstalled it several times, but the problem persists. My Ubuntu version is 20.04.This issue has been bothering me for several days.
![20fc821d6b16d0fc4627436a33e26e13](https://github.com/user-attachments/assets/d6d7a415-2a7b-456f-9ef6-662b536be896)

**Comment by cgokmen** [comment]
#1059 has the same issue, consider updating your glibc.

**Comment by jiangxiaobaiii** [comment]
> #1059 也有同样的问题，请考虑更新您的 glibc。

Thank you, I'll go try it right away.
