### ISSUE TITLE
Human animation?

### ISSUE THREAD

**Issue by youngwoo-yoon** [StanfordVL/OmniGibson#116]
Hello, 
Thanks for the great work.

I found the recent Omniverse has integrated human animation into scenes. 
(see https://docs.omniverse.nvidia.com/app_isaacsim/app_isaacsim/ext_omni_anim_people.html)
Do you have the plan to integrate human animation into OmniGibson?

**Comment by ChengshuLi** [comment]
Hi [youngwoo-yoon](https://github.com/youngwoo-yoon), thanks for sharing with us the human animation extension from Omniverse. We don't have an immediate plan to integrate human animation into OmniGibson, but we receive feedback from many researchers who are interested in having humans in OmniGivson, so we might be able to incorporate this feature in the second half of this year.

**Comment by youngwoo-yoon** [comment]
Thanks, looking forward to that!
