### ISSUE TITLE
Questions about the articulated object's state and the high-level primitive skill

### ISSUE THREAD

**Issue by Murkey8895** [StanfordVL/OmniGibson#136]
Hi, I have some questions when using omnigibson:

1. Is it possible to access some key parts of the articulated objects (e.g. the handle of the cabinet, the door of the microwave) ? If possible, expert demonstration generation can be easy.
2. will the next release support high-level primitive skills mentioned in your paper ?

Thank you very much!

**Comment by ChengshuLi** [comment]
1. If the key parts of the articulated objects is a separate link (e.g. door of the microwave or door handle that can rotate), you can access its pose by querying `obj.links[link_name].get_position_orientation`. 
2. Not in the immediate next release, but it's definitely in our road map. Contribution is also very welcomed!
