### ISSUE TITLE
 [Error] [omni.physx.plugin] Particles feature is only supported on GPU. Please enable GPU dynamics flag in Property/Scene of physics scene!

### ISSUE THREAD

**Issue by michalvavrecka** [StanfordVL/OmniGibson#138]
I am sorry for the stupid question, but I do not know how to enable this feature as the omnigibson crashes during initialization followed by the AttributeError: 'ContactParticles' object has no attribute 'reset in terminal. Is this a bug or does it realate to GPU (RTX2060 card, 525 drivers)?

Thanks

Michal

**Comment by wensi-ai** [comment]
could you try setting `gm.USE_GPU_DYNAMICS = True` in macros.py?

**Comment by ChengshuLi** [comment]
Sorry it's a bug on our end. To resolve the issue of " 'ContactParticles' object has no attribute 'reset" would you mind commenting out the following line for now? We will fix this issue in our next release very soon. Thanks for letting us know!

https://github.com/StanfordVL/OmniGibson/blob/915add3025d8d0dcf72239395c5c386f8548aa64/omnigibson/object_states/object_state_base.py#L89

**Comment by michalvavrecka** [comment]
Thanks, the changes in the master branch did not work, but when I switched to developmental branch, the errors disappeared. I was able to run basic demos with turtlebot, but rest of the robot still waits for the conversion from iGibson.

**Comment by tx871217** [comment]
hi, sry dumb question. i used docker to setup OmniGibson instead of from source. any ideas to switch to dev branch? im facing the same issue. Thanks!

**Comment by wensi-ai** [comment]
Hi @tx871217 , we currently only support main branch for docker install. We will have a new release this week which would update the main branch to og-dev.
