### ISSUE TITLE
can it add language as input?

### ISSUE THREAD

**Issue by Bailey-24** [StanfordVL/OmniGibson#175]
I want to use language to guide to robot. but I don't know the benchmark or whether can add language as input.

**Comment by cremebrule** [comment]
Hi @Bailey-24 ,

`OmniGibson` doesn't directly support language out of the box, but you can create an [Environment wrapper](https://github.com/StanfordVL/OmniGibson/blob/main/omnigibson/wrappers/wrapper_base.py) that implements an additional layer that converts as the top-level text `action` into low-level numerical `action` passed into the native environment.

Closing this issue for now, but feel free to re-open if you continue to run into issues!
