### ISSUE TITLE
'An' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Hollen0318** [StanfordVL/OmniGibson#178]
'An' is not recognized as an internal or external command,
operable program or batch file.

Is it gonna be a problem?

**Comment by Hollen0318** [comment]
It happens after I run the 
"setup_conda_env.bat"

**Comment by wensi-ai** [comment]
Hi @Hollen0318 , could you add `echo` at the beginning of line 52 in setup_conda_env.bat and run the file again? Thanks!

**Comment by wensi-ai** [comment]
Also can you provide the full log if the above doesn't help? You might also need to remove the conda environment `conda env remove -n omnigibson` before running `setup_conda_env.bat` again

**Comment by wensi-ai** [comment]
Bug fixed, will be updated in the next release.
