### ISSUE TITLE
Code for RL-Prim training in the paper

### ISSUE THREAD

**Issue by qianLyu** [StanfordVL/OmniGibson#181]
Hi authors,

Thanks for sharing your wonderful work! I'm wondering if there's any demo reimplementing the RL-Prim training (CollectTrash/CleanTable) shown in the paper?

Thanks in advance!

**Comment by cgokmen** [comment]
This code is not currently released as part of OmniGibson. We are working on a separate set of action primitives that will be available as part of an upcoming release, probably in September.

Same as #238

**Comment by lziiid** [comment]
> This code is not currently released as part of OmniGibson. We are working on a separate set of action primitives that will be available as part of an upcoming release, probably in September.
> 
> Same as #238

Thanks for the wonderful work and open-source code! I wonder if the set of action primitives is available now? I can't find it in the source code :(
