### ISSUE TITLE
Installation on headless machine

### ISSUE THREAD

**Issue by dongyh20** [StanfordVL/OmniGibson#216]
Do we have a tutorial about how to install all the dependencies including omniverse as well as Isaac sim? I got stuck installing omniverse but don't know what to do.

**Comment by cgokmen** [comment]
Sorry we missed this question - we recommend installing via docker. https://behavior.stanford.edu/omnigibson/getting_started/installation.html#__tabbed_1_1

The advantage of this is when we have updates (or Nvidia has for Isaac Sim), you'll be able to get them by simply rerunning the command.

I'm closing this issue - please feel free to reopen if you need anything else.
