### ISSUE TITLE
Tiago's arm motion is very slow when using action primitives

### ISSUE THREAD

**Issue by misoshiruseijin** [StanfordVL/OmniGibson#225]
When using Semantic Action Primitives with Tiago robot, the arm motion is very slow, especially when moving the shoulder joints to lift the arm up. The Fetch robot does not have this problem. Increasing the Kp gain in the ControllableObject class (from default 1e7 to 1e35) only makes it marginally faster. Reducing the arm mass speeds up the arm significantly, but is there a cleaner fix?

**Comment by cgokmen** [comment]
Any idea how this was resolved? I'm closing but feel free to leave a comment.

**Comment by misoshiruseijin** [comment]
I suspect it has to do with GPU and driver versions but I am not completely sure. The arm started moving a lot faster on one of the workstations after updating the graphics driver, but it is not as fast on other workstations.
