### ISSUE TITLE
RL baselines with action primitives in the BEHAVIOR-1K paper

### ISSUE THREAD

**Issue by RedCarp0** [StanfordVL/OmniGibson#238]
Hi,
Thanks for your great work!

I haven't found the code about RL baselines (with action primitives) described in the BEHAVIOR-1K paper (and the Appendix). Will the code be made available later? If so any ETA? Thanks!

**Comment by cgokmen** [comment]
This code is not currently released as part of OmniGibson. We are working on a separate set of action primitives that will be available as part of an upcoming release, probably in September.
