### ISSUE TITLE
Failed to run tutorial example.

### ISSUE THREAD

**Issue by WangYixuan12** [StanfordVL/OmniGibson#254]
Hi! Thank you for your hard work! When I followed the installation instruction [here](https://stanfordvl.github.io/OmniGibson/getting_started/installation.html#setup) and run `python -m omnigibson.examples.scenes.scene_selector`, I encountered the error
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/yixuan/OmniGibson/omnigibson/data/og_dataset/objects/bottom_cabinet/bamfsz/usd/bamfsz.encrypted.usd'
```
I checked the folder. It seems `bottom_cabinet` is missing. But I downloaded og_dataset by following the instruction. Could you please help with this? Thank you in advance for your help!

**Comment by cremebrule** [comment]
Hi @WangYixuan12 ,

Thanks for raising this issue! Did you install from docker or from source?

**Comment by cremebrule** [comment]
I just tried the docker install and I can't reproduce your error -- did you specify a custom DATA_DIR?

**Comment by WangYixuan12** [comment]
Thank you @cremebrule ! I installed from source. Any information I could provide to help you reproduce the error?

**Comment by cremebrule** [comment]
I see -- have you verified that the dataset has been downloaded at all? Or did the dataset fail to download altogether?

**Comment by WangYixuan12** [comment]
I just went through the installation process again. This time the error did not appear. The reason might be that I experienced download interruption for the first time, and resuming downloading did not fully download the whole dataset. Sorry for the confusion!
