### ISSUE TITLE
Sticky mode doesn't work

### ISSUE THREAD

**Issue by 15210579725** [StanfordVL/OmniGibson#262]
When I was running the Robot grasping demo, even though I have chosen sticky mode, but the cube doesn't constrained even I have touched it.
How to use sticky mode properly?

**Comment by cgokmen** [comment]
Can you check if it works well if you switch to the action_primitives branch? We will be merging a few improvements to this system very soon for an upcoming release.

**Comment by cgokmen** [comment]
This feature is confirmed to work in the development version, so I'm closing the issue. Stay on the lookout for our next release!
