### ISSUE TITLE
Combination of BehaviourTasks

### ISSUE THREAD

**Issue by rudrasohan** [StanfordVL/OmniGibson#275]
Hello, 

I wanted to ask if there is a direct way to combine two or more `BehaviorTask` instances (For example if I have tasks "organize groceries" and "bake a cake", can I have an episode which does a combination of them like "organize groceries and then bake a cake"). I saw that the `behaviour_task.py` has a functionality called [`def update_activity`](https://github.com/StanfordVL/OmniGibson/blob/aa8b8701e6abc3f2310a883a0ce2b635405347c7/omnigibson/tasks/behavior_task.py#L210) but I did not see it's use outside the file's init function. Is there a way in which I can achieve this without having to write a separate bddl for the combined task ?

**Comment by cgokmen** [comment]
Sorry we missed this message - there is no way of doing this out of the box. I would recommend writing a separate BDDL (note that you can probably write a program to merge them too by first renaming the object scope objects and then merging the init/goal conds)
