### ISSUE TITLE
got error when running behavior demo

### ISSUE THREAD

**Issue by xdhhh** [StanfordVL/OmniGibson#276]
Hi, when i try to run behavior.env.demo(with Isaac Sim 2022.2.0), i got an error

AttributeError: 'PrimTransformManipulator' object has no attribute '_manipulator'

Is there any solution?

**Comment by cgokmen** [comment]
Hi, sorry we missed this earlier. This error is actually not an error - it's a problem with a part of Omniverse that does not have any effect on OmniGibson. If you are running into other issues please feel free to post that here.
