### ISSUE TITLE
Incorrect sensor return

### ISSUE THREAD

**Issue by StarsTesla** [StanfordVL/OmniGibson#301]
Hello, I am using robot sensors to detect surrounding objects, boxes=self. robot. get_ OBS() ['Fetch: eyes_Camera_sensor_bbox_2d_right '], but I found that the returned Box and object name do not match correctly. This has caused problems with my application because I am unable to correctly recognize and process detected objects.

**Comment by cgokmen** [comment]
I will be investigating this this week - what version of Isaac Sim are you on?

**Comment by StarsTesla** [comment]
2022.0

**Comment by StarsTesla** [comment]
> I will be investigating this this week - what version of Isaac Sim are you on?

2022.0

**Comment by cgokmen** [comment]
Hi, can you give us a script that we can try out to reproduce this issue? We were unable to reproduce this. Sorry for the late response.

**Comment by cgokmen** [comment]
(for OG team: this is related to #458 )

**Comment by ChengshuLi** [comment]
Should be fixed now.
