### ISSUE TITLE
Loading different scenes

### ISSUE THREAD

**Issue by chenjiayi-zxx** [StanfordVL/OmniGibson#322]
Hello, I think there was a problem loading multiple scenarios into the code. I use og. sim. stop() to stop a scene, and when I load the same scene multiple times in the code, there is no problem. However, when I modify the scene's config, IndexError appears: index -4682680005703348206 is out of bounds for axis 0 with size 22.

**Comment by cgokmen** [comment]
Hi, can you explain what you mean by multiple scenarios? You should not call the play/stop functions, they don't do anything you'd be interested in as a user. You can clear the simulator using sim.clear and then create a new Environment instance. Please join our discord channel linked in the readme if you need more help.
