### ISSUE TITLE
Joint rotation occurs during movement

### ISSUE THREAD

**Issue by chenjiayi-zxx** [StanfordVL/OmniGibson#324]
Hello, when I use the fetch robot to make a left turn, why does the joint related to the camera rotate? This has caused me to capture the incorrect camera pose and shooting image. Or, do I have any methods to fix this joint? Thank you.

**Comment by cgokmen** [comment]
It shouldn't - maybe the friction is too low. We would be happy to investigate if you can produce a reproduction script. Regardless - you can use a NullJointController with a fixed default_command value for the camera joint's position target - this should actively drive the camera to the same pose relative to the robot base.
