### ISSUE TITLE
instance segmentaion bug: some obj mislabeled

### ISSUE THREAD

**Issue by RedCarp0** [StanfordVL/OmniGibson#329]
I have noticed that the instance segmentation codes have some bugs. Although most of the instance labels returned by the seg_instance sensor match the label in helpers.get_instance_mappings(), some labels are incorrect, for example, the "floor" objects are often mislabeled. Have you experienced this issue? 

* Omnigibson version: 0.2.1
* (Tested on) Task: re_shelving_library_books
* (Tested on) Scene: Rs_int

**Comment by cgokmen** [comment]
Can you give us a script to reproduce (e.g. produce the image/mapping pair that is wrong)? it would really help. thanks!
