### ISSUE TITLE
Grasping and base movement of robots

### ISSUE THREAD

**Issue by chenjiayi-zxx** [StanfordVL/OmniGibson#332]
Hello, I've encountered some issues while using the Fetch robot. I've been using methods like turn_left to move my robot, but when the robot's manipulator arm grasps objects, the objects often slip out of the arm's control. This problem prevents the robot from moving objects stably. I'm wondering if there are any solutions or best practices to address this issue. Thank you very much for your assistance.

**Comment by cgokmen** [comment]
Hi, can you provide a script to reproduce the issue? Thanks!

**Comment by ChengshuLi** [comment]
Closing the issue for now. Feel free to re-open if you have further questions.

In general, if the grasp is not firm enough during navigation, maybe you can consider using `"assitive"` or "sticky"` grasping_mode (see `manipulation_robot.py` for more details).
