### ISSUE TITLE
IK and Grasping

### ISSUE THREAD

**Issue by chenjiayi-zxx** [StanfordVL/OmniGibson#335]
Hello, I encountered some issues while using ik and grading demo. When using ik, I need to use the 
controller_config={
            "arm_0": {
                "name": "JointController",
                "motor_type": "position",
            }
        }
}
But if this is used, the sticky property of the grafting will have problems. Even if the robot grabs the object, it cannot magnetize it, and I call robot.is_ Grassing(), the result is also false, but I particularly need to combine ik and Grass in my project. I hope to receive your guidance, thank you.

**Comment by cgokmen** [comment]
Hi, for questions please feel free to join our discord and ask there so we can avoid the long back-and-forth loop here. Please also post a minimum reproducible example. Thanks!
