### ISSUE TITLE
how to run omnigibson in a headless mode

### ISSUE THREAD

**Issue by whcpumpkin** [StanfordVL/OmniGibson#362]
Dear authors,
        Can omnigibson run in headless mode?
        I installed omnigibson on a computer with a monitor. Every time I run omnigibson, a window will pop up showing the current running situation. Can I run it silently?
         My fps running omnigibson is only 10 (2080ti), is there any way to improve the fps?
         Many thanks!

**Comment by cgokmen** [comment]
Hi, you can set the OMNIGIBSON_HEADLESS=1 environment variable to avoid that window getting launched. E.g.

```
OMNIGIBSON_HEADLESS=1 python omnigibson/...
```

Re: the FPS you can try enabling the flatcache mode which speeds simulation up drastically (but can't be used with cloth tasks). Simply do this at the top of your script:

```
import omnigibson.macros as gm
gm.ENABLE_FLATCACHE = True
```

**Comment by whcpumpkin** [comment]
![image](https://github.com/StanfordVL/OmniGibson/assets/44776486/10d2e64e-ee19-47e1-9ad3-0f8b045e8a2e)

Hi, when I set `gm.ENABLE_FLATCACHE = True`, it occured an error above. 
Is this parameter set to True only in scenes where there is no clothing?

**Comment by Yonggie** [comment]
> Hi, you can set the OMNIGIBSON_HEADLESS=1 environment variable to avoid that window getting launched. E.g.
> 
> ```
> OMNIGIBSON_HEADLESS=1 python omnigibson/...
> ```
> 
> Re: the FPS you can try enabling the flatcache mode which speeds simulation up drastically (but can't be used with cloth tasks). Simply do this at the top of your script:
> 
> ```
> import omnigibson.macros as gm
> gm.ENABLE_FLATCACHE = True
> ```

Hi, a follow-up question: when in headless mode in ``server A``, is it possible to use Omniverse Streaming Client to visualize the scene in ``server B``? I succeeded to start headless App but failed in connecting the ``server A`` from ``server B``. 

Do I need to set the host to be 0.0.0.0 in ``server A`` kinda staffs? How may I do that?

![图片](https://github.com/user-attachments/assets/21817a23-f025-495a-818f-c7f1a87057a0)

**Comment by Yonggie** [comment]
> > Hi, you can set the OMNIGIBSON_HEADLESS=1 environment variable to avoid that window getting launched. E.g.
> > ```
> > OMNIGIBSON_HEADLESS=1 python omnigibson/...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Re: the FPS you can try enabling the flatcache mode which speeds simulation up drastically (but can't be used with cloth tasks). Simply do this at the top of your script:
> > ```
> > import omnigibson.macros as gm
> > gm.ENABLE_FLATCACHE = True
> > ```
> 
> Hi, a follow-up question: when in headless mode in `server A`, is it possible to use Omniverse Streaming Client to visualize the scene in `server B`? I succeeded to start headless App but failed in connecting the `server A` from `server B`.
> 
> Do I need to set the host to be 0.0.0.0 in `server A` kinda staffs? How may I do that?
> 
> ![图片](https://private-user-images.githubusercontent.com/31330044/379076740-21817a23-f025-495a-818f-c7f1a87057a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTEzMDIsIm5iZiI6MTcyOTY1MTAwMiwicGF0aCI6Ii8zMTMzMDA0NC8zNzkwNzY3NDAtMjE4MTdhMjMtZjAyNS00OTVhLTgxOGYtYzdmMWE4NzA1N2EwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDAyMzY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NjIyM2VmZWVmZWFlYjM2Y2Q3ZmU0MjAzOTZiMThhNGJiZTYwNzk5MGE4NGVkNjY2MzBlMTVjNDE1ODQ1NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iryoGHRhaeV2jzalzwjy6gM6G5CbQtGosTZj9QGiGS0)

I raise the same issue at omnigibson, a more detailed describtion can be found here: https://github.com/StanfordVL/OmniGibson/issues/1005

**Comment by hanlanqian** [comment]
> > Hi, you can set the OMNIGIBSON_HEADLESS=1 environment variable to avoid that window getting launched. E.g.
> > ```
> > OMNIGIBSON_HEADLESS=1 python omnigibson/...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Re: the FPS you can try enabling the flatcache mode which speeds simulation up drastically (but can't be used with cloth tasks). Simply do this at the top of your script:
> > ```
> > import omnigibson.macros as gm
> > gm.ENABLE_FLATCACHE = True
> > ```
> 
> Hi, a follow-up question: when in headless mode in `server A`, is it possible to use Omniverse Streaming Client to visualize the scene in `server B`? I succeeded to start headless App but failed in connecting the `server A` from `server B`.
> 
> Do I need to set the host to be 0.0.0.0 in `server A` kinda staffs? How may I do that?
> 
> ![图片](https://private-user-images.githubusercontent.com/31330044/379076740-21817a23-f025-495a-818f-c7f1a87057a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5MzA5NjUsIm5iZiI6MTczNjkzMDY2NSwicGF0aCI6Ii8zMTMzMDA0NC8zNzkwNzY3NDAtMjE4MTdhMjMtZjAyNS00OTVhLTgxOGYtYzdmMWE4NzA1N2EwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE1VDA4NDQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0NTEwYmQwMjIzYzY0Mzk5MjczN2IxZDNmM2QwYTUyODg3OGI2MjM1ZGVhMGQwMDM0NDI5Nzg4YjJjZjdmZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7BRnPmF9SEW6HN_lhHfzKL4q3i9Y6ZX4mQondgoMj0A)

Hello, I hope you're doing well. I'm experiencing the same issue. Have you been able to resolve it?

**Comment by Yonggie** [comment]
@hanlanqian Sorry it's been quite a while. I can't recall much. I was using ``mobaxterm`` tools to start the service. I  kept encountering ``segmentation fault`` and I might solve this by ``export DISPLAY=13.0``. There's no addtional settings related to OmniGibson to be made.

**Comment by Yonggie** [comment]
@hanlanqian Sorry it's been quite a while. I can't recall much. I was using ``mobaxterm`` tools to start the service. I  kept encountering ``segmentation fault`` and I might solve this by ``export DISPLAY=13.0``. There's no addtional settings related to OmniGibson to be made. 

This was the full log of my case: https://github.com/StanfordVL/OmniGibson/issues/1005

**Comment by hanlanqian** [comment]
> @hanlanqian Sorry it's been quite a while. I can't recall much. I was using `mobaxterm` tools to start the service. I kept encountering `segmentation fault` and I might solve this by `export DISPLAY=13.0`. There's no addtional settings related to OmniGibson to be made.
> 
> This was the full log of my case: #1005

Thanks for replying~🌸 In my case it's ok to connect the remote isaac sim from omniverse streaming client. But I was stuck in the connecting process, I don't know how to connect to remote isaac sim for simulation in omnigibson. Could you please guide me on where should I specify the remote ip in omnigibson code?
