### ISSUE TITLE
Figure out BoundingBoxAPI and get_base_aligned_bbox

### ISSUE THREAD

**Issue by cgokmen** [StanfordVL/OmniGibson#434]
Subtasks:
- [ ] BoundingBoxAPi is based on what? (visible) visual meshes? collision meshes?
- [ ] How to make get_base_aligned_bbox consistent with BoundingBoxAPI?
- [ ] visual=False and fallback_aabb=True should NOT be a valid combination if BoundingBoxAPI aabb is relying on visual meshes?
- [ ] How should (visible and non-visible) meta links be handled in both cases?

**Comment by hang-yin** [comment]
Goal is to replace the USD AABB functionality with our own bb functionality. 

- [ ] in the geom prim class write a property points (maybe this already exists) that returns a matrix containing the local poses of all the points. 

- [ ] then in rigid prim write a cached property that takes all the points from its child geom prims and gets their convex hull and gets the points on the convex hull. 

- [ ] then on entityprim write a function that gets the convex hull points from all of the links and transforms them to world frame and returns the aabb
