### ISSUE TITLE
Improve encryption scheme & USD path saving

### ISSUE THREAD

**Issue by cgokmen** [StanfordVL/OmniGibson#48]
Leaving this as a tracking bug for later. We can improve our encryption scheme such that:

1. Texture maps etc. also get encrypted.
2. We don't do tricks around where files are loaded from (e.g. the USD path will actually be in the tmp dir)
3. We on-demand decrypt additional files using some sort of util library (e.g. need a new material? decrypted right when you need it)
4. We update our current code so that instead of absolute paths (which will no longer make sense), all USD paths contain relative references.

**Comment by cremebrule** [comment]
@cgokmen can we close this?

**Comment by cgokmen** [comment]
I think so
