### ISSUE TITLE
Convert subclassing logic to instance logic for things like particle systems

### ISSUE THREAD

**Issue by cgokmen** [StanfordVL/OmniGibson#590]
refactor these particle systems to be instances of MacroParticleSystem etc. rather than instanceless subclasses. If each particle system is going to be a subclass but each subclass will have only one instance there's no point in them being subclasses imo since they don't implement any logic. This is currently an antipattern in fact and it's really confusing to a new reader that we're generating subclasses based on the contents of a json file somewhere & those subclasses contain no custom logic. We've essentially reimplemented OOP using subclass methods/fields instead of instancing which is weird

this PR could also include some code to move the UniquelyNamed functionality into a proper factory function instead (e.g. make creation of duplicates impossible rather than asserting this way)

**Comment by hang-yin** [comment]
This is issue is being addressed in this branch: [rl-multiple-envs-systems](https://github.com/StanfordVL/OmniGibson/tree/rl-multiple-envs-systems)
