### ISSUE TITLE
Inquiry Regarding Execution of Behavior-1K Examples

### ISSUE THREAD

**Issue by im-renpei** [StanfordVL/OmniGibson#624]
Hi all,

I have successfully installed omniGibson from source on my Linux system following the installation process. But I am facing difficulties in replaying the examples showcased in the video at https://behavior.stanford.edu/assets/img/behavior/b1k_pull_video.mp4 (2:15/3:03), for example, "Filling Cut with Water," "Wiping Table with Cloth," and "Slicing Apple with Knife".

Could you please enlighten me on any steps or details I might be overlooking?

**Comment by ChengshuLi** [comment]
I am not sure if we still have the exact code to reproduce the video you saw.

Feel free to try out different examples in the `omnigibson/examples` folder, e.g. `slicing_demo.py` and `particle_applier_remover_demo.py`, which should serve a similar purpose.
