### ISSUE TITLE
How to train the RL policy through SB-3 MlpPolicy?

### ISSUE THREAD

**Issue by wzjscut** [StanfordVL/OmniGibson#697]
I hope to write a reinforcement learning example by referring to the method in example/learning/navigation_policy_demo.py. I wish to use MlpPolicy to train the policy. But I found that the observations defined in env_base.py are all in Dict format. Is there any way to convert it to Box format?

**Comment by ChengshuLi** [comment]
The task-relevant observation are already flattened and they can be processed by MLPPolicy.

Other observations are from onboard sensors, e.g. rgb, depth, etc., which generally speaking should not be flattened. You should consider using different encoders to process them separately, e.g. Conv2DPolicy.
