### ISSUE TITLE
Does the grasp primitive in the started_semantic_action_primitives work with "physical" grasping mode? 

### ISSUE THREAD

**Issue by Arpitrf** [StanfordVL/OmniGibson#706]
Hello, I tried setting the grasping mode in the "fetch_primtives.yaml" to physical and ran `python -m omnigibson.examples.action_primitives.solve_simple_task`. However, the robot is not able to grasp the object at all in this case. Is this an expected behavior? Is physical grasping mode implemented in started_semantic_action_primitives?

**Comment by cgokmen** [comment]
Not currently. You could implement it by improving how a grasp pose gets sampled. Take a look at the get_grasp_poses_for_object_sticky_from_arbitrary_direction etc functions for how to do this. It is nontrivial to get robust physical grasp poses for arbitrary objects.
