### ISSUE TITLE
Teleoperation using Game Controller

### ISSUE THREAD

**Issue by vantony1** [StanfordVL/OmniGibson#716]
Hi,

I was wondering if tele-operating robots in OmniGibson using a Game Controller is possible? I have looked that the documentation and the code but can't seem to find the keyboard teleoperation file that I could use as a guide to implement the game controller teleop functionality if one is not provided already.

Best,

Victor

**Comment by cgokmen** [comment]
@wensi-ai

**Comment by wensi-ai** [comment]
Yes, using game controller is possible. Take a look at [this script](https://github.com/StanfordVL/OmniGibson/blob/main/omnigibson/utils/teleop_utils.py) where we use [Telemoma](https://github.com/UT-Austin-RobIn/telemoma) for robot teleoperation (you can try out `robot_teleoerate_demo.py` to see how it is used)

Alternatively, [here](https://github.com/StanfordVL/OmniGibson/blob/main/omnigibson/utils/ui_utils.py) is another keyboard interface that is used by `robot_control_example.py`

**Comment by vantony1** [comment]
Thanks so much! I will give it a shot and let you know if I further questions. I appreciate the help.
