### ISSUE TITLE
How to adjust the tilt angle of the camera

### ISSUE THREAD

**Issue by zhaoyaping111** [StanfordVL/OmniGibson#738]

**Comment by ChengshuLi** [comment]
Sorry for the late reply.

Do you mean adjust the tilt angle of the camera on a robot? You can adjust the joint angle of the connecting joint whose child link has the camera sensor attached.

For instance, for the Fetch robot, you can adjust the "head_tilt_joint".

```
robot.joints["head_tilt_joint"].set_pos(np.pi / 6)
```
