### ISSUE TITLE
env.robots[0].sensors['robot0:eyes_Camera_sensor'].get_position_orientation()      env.robots[self._robot_idn].states[Pose].get_value()  What is the difference between these two commands?

### ISSUE THREAD

**Issue by zhaoyaping111** [StanfordVL/OmniGibson#739]

**Comment by zhaoyaping111** [comment]
Why does the value remain unchanged throughout the entire motion of the robot?

**Comment by ChengshuLi** [comment]
Sorry for the late reply.

The first command returns the position and orientation of the camera sensor.
The second command returns the position and orientation of the robot.

I am not sure why the values remain unchanged. They should - as the robot moves. 
Feel free to send a repro script to us. Closing the issue for now.
