### ISSUE TITLE
Any plans to upgrade to issac-sim:4.0.0?

### ISSUE THREAD

**Issue by cailiang9** [StanfordVL/OmniGibson#745]

**Comment by yubinwang11** [comment]
It is noted that there is a branch named 4-0-0-fixes. It is believed about Compatibility fixes for Isaac Sim 4.0.0.

**Comment by cgokmen** [comment]
Yes, but try this at your own risk. It's untested code that I am going to work on soon.

**Comment by cgokmen** [comment]
Closing this issue - the upgrade has been merged to our develop branch if you want to try it out. It will be included in the next release.
