### ISSUE TITLE
docker env code Version

### ISSUE THREAD

**Issue by JiaheXu** [StanfordVL/OmniGibson#80]
Hi OmniGibson developers,

I have tried all the demos in the docker env, and SOME of them cannot work. One of the most common issues is the 
`No openable joint metadata found for object fridge_xyejdx_0`, please take a look.

**Comment by JiaheXu** [comment]
My fault, the code just takes a lot of time to load all the models

**Comment by ChengshuLi** [comment]
Hi @JiaheXu, these warning messages are caused by missing some metadata information for the Openable state for the fridge assets. You can safely ignore these messages for now, as they shouldn't break any example. We will fix the missing metadata in the next release soon. Thanks!

**Comment by JiaheXu** [comment]
Can you please tell me which are the most stable envs/settings to use for now? Thanks
