### ISSUE TITLE
How can make a robot use a tool?

### ISSUE THREAD

**Issue by SresserS** [StanfordVL/OmniGibson#812]
Hi, I want to know how to fix a tool, such as a stick, on the gripper of a robot, such as Franka, and then complete some tasks of using tools. I didn't find any relevant examples. My understanding is that I may need to remodel a robot's urdf file and then load it? Can you provide some reference?

**Comment by cgokmen** [comment]
You can follow this tutorial (note this is in our development branch docs and is WIP) - it follows the import of a brand new robot, you can simply edit the part after the USD if you'd like. https://behavior.stanford.edu/omnigibson-develop/tutorials/custom_robot_import.html

A much simpler alternative is you could just import the object in OmniGibson and attach it to the robot's hand at runtime using the create_joint function.
