### ISSUE TITLE
"omni.isaac.core" not recognized in omnigibson python environment

### ISSUE THREAD

**Issue by krajaei** [StanfordVL/OmniGibson#814]
Hi 
I have attempt to import set_camera_view using the following code in omnigibson environment:
'''
from omni.isaac.core.utils.viewports import set_camera_view

'''
However, it resulted in a error:
'''
 from omni.isaac.core.utils.viewports import set_camera_view
ModuleNotFoundError: No module named 'omni.isaac.core'

'''

Could anyone please help me solve this problem?

**Comment by cgokmen** [comment]
Hi, OmniGibson does a lazy load of the Isaac Sim libraries - you can only import omni modules after you have launched the Simulator. To help you do this, skip the Isaac import, instead do ` import omnigibson.lazy as lazy`. Then where you're going to call set_camera_view, call it as `lazy.omni.isaac.core.utils.viewports.set_camera_view(...)`.

I do want to let you know however that this is probably not the best way of setting the camera view in OmniGibson (in fact we recommend the user does not call **any** Isaac Sim functions directly). The viewport camera is an object managed by OmniGibson and moving it this way might have unintended consequences. I'd simply set the pose of the camera by doing `og.sim.viewer_camera.set_position_orientation(...)`

**Comment by krajaei** [comment]
Thank you!
The problem has been resolved.

Could you please help me solve another error when importint "BoundingBoxAPI":
''''
from omnigibson.utils.usd_utils import BoundingBoxAPI
ImportError: cannot import name 'BoundingBoxAPI' from 'omnigibson.utils.usd_utils' (/home/user1/OmniGibson/omnigibson/utils/usd_utils.py)
'''

**Comment by cgokmen** [comment]
When/where are you trying to import this & why?

**Comment by ChengshuLi** [comment]
Feel free to re-open the issue if the problem persists, thanks!
