### ISSUE TITLE
Does OmniGibson have some predefined high-level actions?

### ISSUE THREAD

**Issue by shengyin1224** [StanfordVL/OmniGibson#820]
Hi guys, I am very excited for the OmniGibson simulator and want to try instruction following task in the platform. Therefore, I am wondering if there are some already created high-level actions like 'open', 'switchon' for interacting objects. I only find the action space of a type of robot is a vector to control the low-level motion.

-----------------------------------------------------------------------------------------

I  found 'symbolic_semantic_action_primitives' and 'starter_semantic_action_primitives' in the doc. I wanna know the difference between these two and it seems that the first one supports more high-level actions

**Comment by hang-yin** [comment]
@cgokmen can best answer this.

**Comment by ge79puv** [comment]
Hi, I have the same question. Any updates?

**Comment by cgokmen** [comment]
You can use the action primitives which are now included in OmniGibson. You will need OMPL to use them so just start with the Docker container. There are examples in the examples/action_primitives directory, and you can find out more about the full set of primitives in the omnigibson/action_primitives directory. We have a physically simulated set and a symbolic, teleporting set.

**Comment by yananchen1989** [comment]
@cgokmen 

hi author, in omnigibson, are there any methods to create higher level actions, such as wipe, rinse, pour, clean etc ?

(I want the VLM/LLM-powered robot  to generate high-level actions with semantic meaning)

thanks.

**Comment by shengyin1224** [comment]
> [@cgokmen](https://github.com/cgokmen)
> 
> hi author, in omnigibson, are there any methods to create higher level actions, such as wipe, rinse, pour, clean etc ?
> 
> (I want the VLM/LLM-powered robot to generate high-level actions with semantic meaning)
> 
> thanks.

They seem to provide some high-level actions in starter_semantic_action_primitives.py
