### ISSUE TITLE
Adjusting Scene Lighting 

### ISSUE THREAD

**Issue by krajaei** [StanfordVL/OmniGibson#832]
Hi 
Is there a way to adjust lighting in scenes?

**Comment by hang-yin** [comment]
If you want to adjust lighting for all light sources in a scene, an easy way to do this is to adjust the `gm.FORCE_LIGHT_INTENSITY` constant in the `omnigibson/macros.py` file. Let me know if that works!

**Comment by krajaei** [comment]
Thank you for your response. It works, although I've found that it requires adjusting before loading a scene. I was wondering if it is possible to dynamically adjust the lighting after the scene has been loaded?

**Comment by hang-yin** [comment]
From our `omnigibson.utils.ui_utils`, there's a `CameraMover` class. You can try this:

1. grab the `viewer_camera` instance 
2. create a `CameraMover` with it
3. call `change_light` or `set_light` on the `CameraMover` object

**Comment by ChengshuLi** [comment]
Feel free to re-open the issue if the problem persists, thanks!
