### ISSUE TITLE
AttributeError: module 'gym.spaces' has no attribute 'Sequence'

### ISSUE THREAD

**Issue by mengxyokok** [StanfordVL/OmniGibson#877]
install_requires:
"gym~=0.26.2" 

packages in environment at /envs/omnigibson:
gym                       0.26.2                   pypi_0    pypi
gym-notices               0.0.8                    pypi_0    pypi

gym version is right, but AttributeError: module 'gym.spaces' has no attribute 'Sequence'

**Comment by hang-yin** [comment]
Hi @mengxyokok , thanks for reaching out! Could you please provide the name of the branch you're working on and the specific script that's causing this error?

**Comment by ChengshuLi** [comment]
Unfortunately, we are unable to reproduce this issue on our end. Feel free to re-open the issue if the problem persists, thanks!
