### ISSUE TITLE
Noise in the rgb observation.

### ISSUE THREAD

**Issue by Hoyyyaard** [StanfordVL/OmniGibson#890]
![Snipaste_2024-09-18_21-03-51](https://github.com/user-attachments/assets/4de8d932-c9ff-44a8-92f7-f262732dc100)
I ran the env in the headless mode.

**Comment by hang-yin** [comment]
Duplicated issue on Discord support channel has been addressed:  https://discord.com/channels/1166422812160966707/1166422812160966710/1285954771681017968
