### ISSUE TITLE
Abstract action space support

### ISSUE THREAD

**Issue by ishikasingh** [StanfordVL/OmniGibson#90]
I have a couple questions:

1. Does the current sim version support abstract action spaces like pick/place/open/close?
2. Is it possible to train hierarchical policies?
3. Is it feasible to define motion controllers to implement the above abstract actions - so it's possible to ablate the performance with ground truth low-level actions for plans defined in the abstract action space?

Thanks!

**Comment by cgokmen** [comment]
We are in the process of implementing these features and will release an abstract action space implementation in an upcoming release, probably in September.
