### ISSUE TITLE
No module named omnigibson.install

### ISSUE THREAD

**Issue by idlesilver** [StanfordVL/OmniGibson#931]
Following the installation on https://behavior.stanford.edu/omnigibson/getting_started/installation.html#__tabbed_1_3, I met an error in step 4, "No module named omnigibson.install". I find the `omnigibson/install.py` is only avaliable in the "og-develop" branch but not in the "main" branch. The `git clone` command in quick start guidance didn't fetch the `install.py` file. 

I created a `install.py` file under dir "omnigibson/" and copy the content from "og-develop" branch to solve the problem

**Comment by cgokmen** [comment]
Hey, I think you are doing something wrong in the process of cloning, that file is indeed on `main`: https://github.com/StanfordVL/OmniGibson/blob/main/omnigibson/install.py
