### ISSUE TITLE
Error when running python -m omnigibson.examples.learning.navigation_policy_demo

### ISSUE THREAD

**Issue by ge79puv** [StanfordVL/OmniGibson#940]
Hey there, 

I just used Isaac Sim 4.1.0 and the new released OmniGibson v 1.1.1. I tried to run the demo of RL. However, there is an error: 

![image](https://github.com/user-attachments/assets/0f0d8471-3635-41e9-ab2a-b39f00d0d15c)

Could you help me to solve this issue?

Best regards

**Comment by ChengshuLi** [comment]
Could you let us know the version of `gymnasium`?

**Comment by ge79puv** [comment]
0.29.1

**Comment by ChengshuLi** [comment]
Hmm I am actually not able to reproduce your issue. Maybe you can take a closer look at `obs.spaces`? If it's not `OrderedDict`, what is it?

**Comment by ge79puv** [comment]
I downgrade my gymnasium version, now it works. Thanks a lot!

**Comment by ge79puv** [comment]
Hi,

this omnigibson.examples.learning.navigation_policy_demo sometimes runs fine, but sometimes it suddenly terminates after running for a while. I have not modified any source code, and the error message is as follows: 
![image](https://github.com/user-attachments/assets/03af6612-0896-40b9-9ad9-1cbd8ce85fc1)
I cannot understand why the tensors are loaded on two gpus. And this termination is uncertain. Sometimes this error appears at the beginning, and sometimes it appears after running for a period of time, which makes me unable to complete the entire RL training.

Best regards
