### ISSUE TITLE
BehaviorRobot from Behavior-100?

### ISSUE THREAD

**Issue by yukw777** [StanfordVL/OmniGibson#96]
I couldn't find any mention of [BehaviorRobot](https://stanfordvl.github.io/behavior/agents.html#behaviorrobot) in the doc, so I'm assuming it hasn't been implemented. Is there any plan to implement it? Possibly related to the effort for https://github.com/StanfordVL/OmniGibson/issues/75?

**Comment by cgokmen** [comment]
Yes, this is very much in the plans! Just so we can plan around it, what's your use case?

Also CC @wensi-ai

**Comment by yukw777** [comment]
I was trying to see if BehaviorRobot can be used to model human task execution.

**Comment by wensi-ai** [comment]
Hi @yukw777, we are actively developing and fine tuning BehaviorRobot and will be releasing it with our VR support!
